print("Hello, my name is Duy")
print("I am enjoying it so far!")
print("I am learning Python and it's really fun!")
print("I am excited to see what I can create with Python in the future!")
print("I am looking forward to learning more about Python and its applications.")
print("I am also interested in exploring other programming languages and frameworks.")
print("I believe that programming is a powerful tool that can help me solve complex problems and create innovative solutions.")
print("I am eager to continue my journey in programming and make a positive impact with my skills.")
print("I am also interested in exploring other programming languages and frameworks.")
print("I believe that programming is a powerful tool that can help me solve complex problems and create innovative solutions.")
print("I am eager to continue my journey in programming and make a positive impact with my skills.")            